# Generated by Django 4.2.5 on 2023-10-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_follow_post_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.IntegerField()),
                ("user", models.IntegerField()),
            ],
        ),
    ]
