# Generated by Django 4.2.5 on 2023-09-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='listing_title',
            field=models.CharField(default='title', max_length=64),
            preserve_default=False,
        ),
    ]
