# Generated by Django 4.2.5 on 2023-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_user_id',
            field=models.CharField(max_length=64),
        ),
    ]
